tracd:
  image: wagnerpinheiro/tracd
  ports:
    - "81:8080"
  volumes:
    - "/home/wagner/workspace/docker-trac/trac:/trac"
  env_file:
    - "./secrets/auth.env"
  restart: always
  # net: "host"
  # mem_limit: 1g 